### PR TITLE
Refactor 1

### PR DESCRIPTION
**Pull request by redkite1**
You can have some details on issue #46

### CODE REVIEW

**Comment by redkite1** [comment]
Note: Travis is currently just testing that build of docker images doesn't fail.

**Comment by lawrencegripper** [comment]
Cool, pulled this down and some tests appear to run, hope you don't mind I fixed a few path errors in the test files.  

One odd things around the k8s client which I need to look at. Originally thought it was a version mismatch so tried using dep to pin a version but didn't seem to fix. 

TestOutput 

```
FAIL	github.com/lawrencegripper/ion/internal/app/dispatcher/providers [build failed]
time="2018-05-02T13:49:31+01:00" level=info msg="Sidecar configured"
=== RUN   TestCommitBlob
time="2018-05-02T13:49:31+01:00" level=info msg="Committed blobs" correlationID=frank eventID=01010101 executionID=d7fba6d4-4db6-4a8b-a726-59300590a41f name=testModule timestamp="2018-05-02 13:49:31.986987442 +0100 BST m=+0.002286293"
time="2018-05-02T13:49:31+01:00" level=info msg="Committed blobs" correlationID=frank eventID=01010101 executionID=d7fba6d4-4db6-4a8b-a726-59300590a41f name=testModule timestamp="2018-05-02 13:49:31.987283417 +0100 BST m=+0.002582304"
--- PASS: TestCommitBlob (0.00s)
=== RUN   TestCommitMeta
time="2018-05-02T13:49:31+01:00" level=info msg="Committed metadata" correlationID=frank eventID=01010101 executionID=d7fba6d4-4db6-4a8b-a726-59300590a41f name=testModule timestamp="2018-05-02 13:49:31.987673456 +0100 BST m=+0.002972323"
--- PASS: TestCommitMeta (0.00s)
=== RUN   TestCommitEvents
--- PASS: TestCommitEvents (0.00s)
PASS
ok  	github.com/lawrencegripper/ion/internal/app/sidecar/app/tests	0.010s
=== RUN   TestAzureIntegration
--- SKIP: TestAzureIntegration (0.00s)
	azure_intergration_test.go:32: Skipping integration test in short mode...
=== RUN   TestDevIntegration
--- SKIP: TestDevIntegration (0.00s)
	dev_integration_test.go:27: Skipping integration test in short mode...
PASS
ok  	github.com/lawrencegripper/ion/internal/app/sidecar/integration	(cached)
=== RUN   TestIsValidEvent
--- PASS: TestIsValidEvent (0.00s)
=== RUN   TestJoinBlobPath
--- PASS: TestJoinBlobPath (0.00s)
=== RUN   TestRemoveFile
--- PASS: TestRemoveFile (0.00s)
=== RUN   TestClearDir
--- PASS: TestClearDir (0.01s)
=== RUN   TestCompareHash
--- PASS: TestCompareHash (0.00s)
PASS
ok  	github.com/lawrencegripper/ion/internal/app/sidecar/types/tests	(cached)
=== RUN   TestIntegrationNewListener
--- SKIP: TestIntegrationNewListener (0.00s)
	listener_integration_test.go:42: Skipping integration test in short mode...
=== RUN   TestIntegrationRequeueReleasedMessages
--- SKIP: TestIntegrationRequeueReleasedMessages (0.00s)
	listener_integration_test.go:109: Skipping integration test in short mode...
=== RUN   TestAmqpConnectionStringGeneration
--- PASS: TestAmqpConnectionStringGeneration (0.00s)
=== RUN   TestAmqpConnectionStringEncoding
--- PASS: TestAmqpConnectionStringEncoding (0.00s)
=== RUN   TestGetSubscriptionName
--- PASS: TestGetSubscriptionName (0.00s)
=== RUN   TestGetSubscriptionAmqpPath
--- PASS: TestGetSubscriptionAmqpPath (0.00s)
PASS
ok  	github.com/lawrencegripper/ion/internal/pkg/servicebus	(cached)
FAIL	github.com/lawrencegripper/ion/internal/app/dispatcher/providers [build failed]
time="2018-05-02T13:49:47+01:00" level=info msg="Sidecar configured"
=== RUN   TestCommitBlob
time="2018-05-02T13:49:47+01:00" level=info msg="Committed blobs" correlationID=frank eventID=01010101 executionID=0cf7ac61-d07d-4e19-8172-c1794a778041 name=testModule timestamp="2018-05-02 13:49:47.329425069 +0100 BST m=+0.009433298"
time="2018-05-02T13:49:47+01:00" level=info msg="Committed blobs" correlationID=frank eventID=01010101 executionID=0cf7ac61-d07d-4e19-8172-c1794a778041 name=testModule timestamp="2018-05-02 13:49:47.329842871 +0100 BST m=+0.009851118"
--- PASS: TestCommitBlob (0.00s)
=== RUN   TestCommitMeta
time="2018-05-02T13:49:47+01:00" level=info msg="Committed metadata" correlationID=frank eventID=01010101 executionID=0cf7ac61-d07d-4e19-8172-c1794a778041 name=testModule timestamp="2018-05-02 13:49:47.330202397 +0100 BST m=+0.010210642"
--- PASS: TestCommitMeta (0.00s)
=== RUN   TestCommitEvents
--- PASS: TestCommitEvents (0.00s)
PASS
ok  	github.com/lawrencegripper/ion/internal/app/sidecar/app/tests	0.013s
=== RUN   TestAzureIntegration
--- SKIP: TestAzureIntegration (0.00s)
	azure_intergration_test.go:32: Skipping integration test in short mode...
=== RUN   TestDevIntegration
--- SKIP: TestDevIntegration (0.00s)
	dev_integration_test.go:27: Skipping integration test in short mode...
PASS
ok  	github.com/lawrencegripper/ion/internal/app/sidecar/integration	(cached)
=== RUN   TestIsValidEvent
--- PASS: TestIsValidEvent (0.00s)
=== RUN   TestJoinBlobPath
--- PASS: TestJoinBlobPath (0.00s)
=== RUN   TestRemoveFile
--- PASS: TestRemoveFile (0.00s)
=== RUN   TestClearDir
--- PASS: TestClearDir (0.01s)
=== RUN   TestCompareHash
--- PASS: TestCompareHash (0.00s)
PASS
ok  	github.com/lawrencegripper/ion/internal/app/sidecar/types/tests	(cached)
=== RUN   TestIntegrationNewListener
--- SKIP: TestIntegrationNewListener (0.00s)
	listener_integration_test.go:42: Skipping integration test in short mode...
=== RUN   TestIntegrationRequeueReleasedMessages
--- SKIP: TestIntegrationRequeueReleasedMessages (0.00s)
	listener_integration_test.go:109: Skipping integration test in short mode...
=== RUN   TestAmqpConnectionStringGeneration
--- PASS: TestAmqpConnectionStringGeneration (0.00s)
=== RUN   TestAmqpConnectionStringEncoding
--- PASS: TestAmqpConnectionStringEncoding (0.00s)
=== RUN   TestGetSubscriptionName
--- PASS: TestGetSubscriptionName (0.00s)
=== RUN   TestGetSubscriptionAmqpPath
--- PASS: TestGetSubscriptionAmqpPath (0.00s)
PASS
ok  	github.com/lawrencegripper/ion/internal/pkg/servicebus	(cached)
```

**Comment by redkite1** [comment]
@lawrencegripper thanks for that! Yep, as mentioned, we didn't took care at tests yet :-/

**Comment by lawrencegripper** [comment]
I'm re-introducing `dep` as the k8s dependencies have to all line up (go get just brings down master) - sound ok? This fixes the tests and then have added them back into the make file so they run as part of the CI.

**Pull request merged**
