### PR TITLE
Terraform deployment model for system

### PR DESCRIPTION
**Pull request by lawrencegripper**

### CODE REVIEW

**Comment by lawrencegripper** [comment]
@jjcollinge What structure will the management API look for in the secrets it uses? I'm hoping to update the deployment config to pre-create the necessary secrets with the cosmos, storage keys etc then create an instance of the management API

**Comment by lawrencegripper** [comment]
Blocked on #120

**Comment by jjcollinge** [comment]
Add ACR deployment to the template

**Comment by jjcollinge** [comment]
Also app insights

**Comment by lawrencegripper** [comment]
@jjcollinge Added those in an refactored. I've left the management image provisioning as TBH, think it's best we merge both this and #120 and test together. Sound like a good plan? ps. can you do a review of my terraform?

**Pull request merged**
